name: CI/CD Pipeline DynamicLink

on:
  push:
    branches:
      - dev

jobs:
  Run-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          working-directory:

      - name: Install Dependencies
        run: yarn -i
      # - name: Checkout Repository
      #   uses: actions/checkout@v2

      - name: Check if Repository is Cloned
        run: |
          if [ -d "${{ github.workspace }}" ]; then
            echo "Repository exists."
          else
            echo "Repository does not exist."
          fi
      # - name: check node version
      #   run: |
      #     ls
      #     pwd
      #     # git -v
      #     # git branch
      #     # git status
      #     # git init
      #     # git branch
      #     ls -R $HOME/work/DynamicLinkAlternative/DynamicLinkAlternative

      # - name: Run Tests
      #   run: npm test

      # - name: Deploy to Production
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: |
      #     # Add deployment steps here
